import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import playStore from '../public/images/playStore.png'
import appStore from '../public/images/appleStore.png'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Healing Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link href="https://fonts.googleapis.com/css2?family=Kalam&display=swap" rel="stylesheet"></link>
        {/* <link href="https://fonts.googleapis.com/css2?family=Kalam:wght@700&display=swap" rel="stylesheet"></link> */}

        {/* Tailwind Element */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" />

      </Head>
      {/* <Script src="https://cdn.tailwindcss.com"></Script> */}
      <Script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></Script>

      <nav className='fixed w-full px-3 py-3 font-bold text-white bg-black font-kalam md:px-16 bg-opacity-30'>
        <div className='flex items-center justify-between'>
          <div className='flex'>
            <Link href="">
              <a className='flex-wrap transition hover:text-yellow hover:scale-125'>Healing Time</a>
            </Link>
          </div>
          <div className='hidden space-x-5 md:flex'>
            <Link href="">
              <a className='flex-wrap transition hover:text-yellow hover:scale-125'>Home</a>
            </Link>
            <Link href="#tentang">
              <a className='flex-wrap transition hover:text-yellow hover:scale-125'>Tentang</a>
            </Link>
            <Link href="#fitur">
              <a className='flex-wrap transition hover:text-yellow hover:scale-125'>Fitur</a>
            </Link>
            <Link href="#kontak">
              <a className='flex-wrap transition hover:text-yellow hover:scale-125'>Kontak</a>
            </Link>
          </div>
          <div className=''>
            <Link href="">
              <a className='items-center hidden px-3 py-1 transition border-2 rounded-full hover:bg-yellow border-purple hover:text-black md:flex'>
                Get Started
              </a>
            </Link>
            <p className="mb-4 space-y-1 md:space-x-1 md:space-y-0 md:hidden">
              <button className="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Menu
              </button>
            </p>
          </div>
        </div>

        {/* Header Mobile */}
        <div className="collapse" id="collapseExample">
          <Link href="">
            <a className='flex-wrap transition hover:text-yellow hover:scale-125'>Home</a>
          </Link>
          <Link href="">
            <a className='flex-wrap transition hover:text-yellow hover:scale-125'>About Us</a>
          </Link>
          <Link href="">
            <a className='flex-wrap transition hover:text-yellow hover:scale-125'>Feature</a>
          </Link>
          <Link href="">
            <a className='flex-wrap transition hover:text-yellow hover:scale-125'>Contact</a>
          </Link>
          <Link href="">
            <a className='items-center hidden px-3 py-1 transition border-2 rounded-full hover:bg-yellow border-purple hover:text-black md:flex'>
              Get Started
            </a>
          </Link>
        </div>
      </nav>


      <div className='flex items-center w-full h-screen text-white bg-gradient-to-tr from-black via-purple to-blue-600 font-kalam'>
        <div className='w-1/2 pl-16'>
          <p className='mb-5 text-3xl font-bold'>Bingung cari tempat buat healing..? <br></br> App Healing Time solusinya.</p>

          <p className=''>Mulai perjalanan Kamu dengan satu klik, <br></br> dan cari tempat indah di garut dengan detail fasilitas yang Kamu butuhkan..!</p>
          <div className='flex mt-10 space-x-3'>
            <Link href="">
              <a>
                <img src='/images/apleStore.png' alt="as" className='w-32 transition hover:scale-110' />
              </a>
            </Link>
            <Link href="">
              <a>
                <img src='/images/playStore.png' alt="as" className='w-32 transition hover:scale-110' />
              </a>
            </Link>
          </div>
        </div>
        <div className='w-1/2'>
          <img src='/images/discover.png' alt="as" className='mx-auto transition w-96 hover:scale-110' />
        </div>
      </div>

      <div className='w-full pt-16 text-white h-fit bg-gradient-to-br from-black via-purple to-blue-600 font-kalam'>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#ffffff" fill-opacity="1" d="M0,288L48,272C96,256,192,224,288,197.3C384,171,480,149,576,165.3C672,181,768,235,864,250.7C960,267,1056,245,1152,250.7C1248,256,1344,288,1392,304L1440,320L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path></svg>
      </div>



      <div className='px-10' id='tentang'>
        <div className='flex items-center w-full'>
          <div className='w-2/5 px-5 font-kalam'>
            <p className='mb-10 text-4xl font-medium text-center'>
              Tentang Kami
            </p>
            <p className='text-justify indent-10'>
              Aplikasi <b><q>Healing Time</q></b> merupakan sebuah aplikasi yang menyediakan berbagai macam detail wisata yang ada di <b>Garut</b>, baik itu wisata air, wisata kuliner sampai ke wisata jeep yang ada di Garut.
            </p>
            <p className='text-justify indent-10'>
              Selain itu aplikasi <q>Healing Time</q> juga menyediakan wadah bagi siapa saja untuk menyewakan alat alat yang biasanya di butuhkan di tempat wisata, muai dari kamera, alat kemping, alat renang, dan masih banyak lagi pilihan alat lainnya.
            </p>
          </div>
          <div className='w-3/5 px-5 w- h-fit font-kalam'>
            <div className='justify-center -ml-16 space-y-3 text-center'>
              <img src='/images/leuwijurig.jpg' alt="leuwi jurig" className='w-1/3 mx-auto transition rounded-full hover:scale-110' />
              <p>Wisata Air Leuwi Jurig</p>
            </div>
            <div className='space-y-3 text-center'>
              <img src='/images/ceplak.jpg' alt="as" className='w-1/4 transition rounded-full -mt-28 hover:scale-110' />
              <p className='w-1/4'>Wisata Kuliner Ceplak</p>
            </div>
            <div className='flex justify-end -mt-48 text-center'>
              <div className='w-2/5 space-y-3'>
                <img src='/images/jeep.jpg' alt="as" className='block transition rounded-full hover:scale-110' />
                <p className='block'>Wisata Offroad Jeep</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className='flex items-center w-full px-10 mt-32 text-blackh-fit font-kalam' id='fitur'>
        <div className='w-1/3'>
          <img src='/images/ilustrasi.png' alt="as" className='mx-auto transition w-96 hover:scale-110' />
        </div>
        <div className='w-3/4 px-5'>
          <p className='mb-3 text-3xl font-medium text-center'>
            Kenapa harus pake Aplikasi Healing Time..?
          </p>
          {/* <img src="/images/mockup/splash.png " alt="wa" className='w-72' /> */}
          <p className='text-justify indent-10 px-10'>
            Nikmati pengalaman berbeda di setiap tempat yang Anda kunjungi di garut, temukan petualangan baru dan terjangkau dengan menggunakan aplikasi <b><q>Healing Time</q></b>. Karna kami menyediakan fitur fitur dibawah yang  tentunya dapat membantu Anda untuk menemukan tempat yang cocok untuk healing.
          </p>

          <div className='flex justify-center space-x-8 text-center mt-14 font-bold'>
            <div className='space-y-3'>
              <img src='/images/detail.png' alt="as" className='transition h-24 hover:scale-110 mx-auto' />
              <p>Informasi Detail Wisata</p>
            </div>

            <div className='space-y-3'>
              <img src='/images/fasilitas.png' alt="as" className='transition h-24 hover:scale-110 mx-auto' />
              <p>Informasi Fasilitas Wisata</p>
            </div>

            <div className='space-y-3'>
              <img src='/images/ticket.png' alt="as" className='transition h-24 hover:scale-110 mx-auto' />
              <p>CheckOut Tiket Masuk</p>
            </div>

            <div className='space-y-3'>
              <img src='/images/rental.png' alt="as" className='transition h-24 hover:scale-110 mx-auto' />
              <p>Sewa Alat-alat</p>
            </div>
          </div>
        </div>
      </div>




      {/* <div className='w-full px-10 text-blackh-fit font-kalam'>
        <p className='mb-10 text-4xl font-medium text-center'>
          Fitur
        </p>
        <div className='flex'>
          <div className='w-1/2 px-5'>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Expedita illo nisi distinctio est nemo odio aspernatur neque. Magni perferendis assumenda cupiditate vitae rerum ex tenetur mollitia harum, eum quisquam officia.
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Necessitatibus, dolores ratione incidunt rem repellendus qui? Distinctio odio optio tempora perspiciatis quis commodi error rem quibusdam ducimus impedit et, quae vel!
            </p>
          </div>
          <div className='w-1/2 px-5'>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Expedita illo nisi distinctio est nemo odio aspernatur neque. Magni perferendis assumenda cupiditate vitae rerum ex tenetur mollitia harum, eum quisquam officia.
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Necessitatibus, dolores ratione incidunt rem repellendus qui? Distinctio odio optio tempora perspiciatis quis commodi error rem quibusdam ducimus impedit et, quae vel!
            </p>
          </div>
        </div>
      </div> */}


      {/* <div>
        <img src='/images/plan.png' alt="as" className='w-5/6 px-16 mx-auto transition' />
      </div> */}

      <div className='w-full h-screen bg-gradient-to-b from-white to-purple flex justify-evenly text-center pt-28 text-white font-kalam font-bold'>

        <div className='space-y-3'>
          <img src="/images/mockup/splash.png " alt="wa" className='w-56 transition hover:scale-110' />
          <p>---</p>
        </div>

        <div className='space-y-3'>
          <img src="/images/mockup/detailwisata.png " alt="wa" className='w-56 transition hover:scale-110' />
          <p>Detail Wisata</p>
        </div>

        <div className='space-y-3'>
          <img src="/images/mockup/sewa.png " alt="wa" className='w-56 transition hover:scale-110' />
          <p>Sewa Alat-alat</p>
        </div>

        <div className='space-y-3'>
          <img src="/images/mockup/tour.png " alt="wa" className='w-56 transition hover:scale-110' />
          <p>Tour Guid</p>
        </div>

      </div>


      <footer className='pb-16 w-fuh-fit'>

        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
          <path fill="#5C40CC" fill-opacity="1" d="M0,32L48,37.3C96,43,192,53,288,53.3C384,53,480,43,576,64C672,85,768,139,864,144C960,149,1056,107,1152,85.3C1248,64,1344,64,1392,64L1440,64L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z">
          </path>
        </svg>

        <div className='flex w-full -mt-28 space-x-10 px-10'>
          <div className='w-2/5'>
            <img src='/images/logo.png' alt="as" className='w-1/2 px-16 mx-auto transition' />
            {/* <p className='text-xl font-bold text-center font-kalam'> Healing Time</p> */}
          </div>

          <div className='w-1/5 font-kalam'>
            <p className="text-xl font-bold">Fitur</p>
            <div className='w-full h-1 rounded-full bg-purple pr-8'></div>
            <ul className="space-y-2 pt-5">
              <li className='list-disc'>Detail Wisata</li>
              <li className='list-disc'>Detail Fasilitas</li>
              <li className='list-disc'>Sewa Alat</li>
              <li className='list-disc'>Sewa Tour Guide</li>
            </ul>
          </div>

          <div className='w-1/5 font-kalam'>
            <p className="text-xl font-bold">Sosial Media</p>
            <div className='w-full h-1 rounded-full bg-purple pr-3'></div>
            <div className='block space-y-2 pt-5'>
              <div className='hover:text-purple group'>
                <div className='group-hover:translate-x-3 flex items-center space-x-3 transition-all'>
                  <img src="/icon/ig.png " alt="wa" className='w-5' />
                  <Link href="">
                    <a className='block transition-all'>healingtime.official</a>
                  </Link>
                </div>
              </div>

              <div className='hover:text-purple group'>
                <div className='group-hover:translate-x-3 flex items-center space-x-3 transition-all'>
                  <img src="/icon/facebook.png " alt="wa" className='w-5' />
                  <Link href="">
                    <a className='block transition-all'>healingtime.official</a>
                  </Link>
                </div>
              </div>

              <div className='hover:text-purple group'>
                <div className='group-hover:translate-x-3 flex items-center space-x-3 transition-all'>
                  <img src="/icon/youtube.png " alt="wa" className='w-5' />
                  <Link href="">
                    <a className='block transition-all'>healingtime.official</a>
                  </Link>
                </div>
              </div>
            </div>
          </div>



          <div className='w-1/5 font-kalam' id='kontak'>
            <p className="text-xl font-bold">Kontak</p>
            <div className='w-full h-1 rounded-full bg-purple pr-3'></div>
            <div className='block space-y-2 pt-5'>
              <div className='hover:text-purple group'>
                <div className='group-hover:translate-x-3 flex items-center space-x-3 transition-all'>
                  <img src="/icon/email.png " alt="wa" className='w-5' />
                  <Link href="">
                    <a className='block transition-all'>admin@healingofficial.com</a>
                  </Link>
                </div>
              </div>

              <div className='hover:text-purple group'>
                <div className='group-hover:translate-x-3 flex items-center space-x-3 transition-all'>
                  <img src="/icon/wa.png " alt="wa" className='w-5' />
                  <Link href=" https://wa.me/081212499612">
                    <a className='block transition-all'>+6281 212 499 612</a>
                  </Link>
                </div>
              </div>

            </div>
          </div>


        </div>

      </footer>
    </>
  )
}

export default Home
